/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new PlayerText:gHealthText[MAX_PLAYERS];
new PlayerText:gHungerText4[MAX_PLAYERS];
new PlayerText:gArmorText[MAX_PLAYERS];

//TEXTDRAWS
gHealthText[playerid] = CreatePlayerTextDraw(playerid, 578.000000, 66.000000, "100");
PlayerTextDrawFont(playerid, gHealthText[playerid], 2);
PlayerTextDrawLetterSize(playerid, gHealthText[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, gHealthText[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, gHealthText[playerid], 1);
PlayerTextDrawSetShadow(playerid, gHealthText[playerid], 0);
PlayerTextDrawAlignment(playerid, gHealthText[playerid], 2);
PlayerTextDrawColor(playerid, gHealthText[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, gHealthText[playerid], 255);
PlayerTextDrawBoxColor(playerid, gHealthText[playerid], 50);
PlayerTextDrawUseBox(playerid, gHealthText[playerid], 0);
PlayerTextDrawSetProportional(playerid, gHealthText[playerid], 1);
PlayerTextDrawSetSelectable(playerid, gHealthText[playerid], 0);

gHungerText4[playerid] = CreatePlayerTextDraw(playerid, 578.000000, 55.000000, "100");
PlayerTextDrawFont(playerid, gHungerText4[playerid], 2);
PlayerTextDrawLetterSize(playerid, gHungerText4[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, gHungerText4[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, gHungerText4[playerid], 1);
PlayerTextDrawSetShadow(playerid, gHungerText4[playerid], 0);
PlayerTextDrawAlignment(playerid, gHungerText4[playerid], 2);
PlayerTextDrawColor(playerid, gHungerText4[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, gHungerText4[playerid], 255);
PlayerTextDrawBoxColor(playerid, gHungerText4[playerid], 50);
PlayerTextDrawUseBox(playerid, gHungerText4[playerid], 0);
PlayerTextDrawSetProportional(playerid, gHungerText4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, gHungerText4[playerid], 0);

gArmorText[playerid] = CreatePlayerTextDraw(playerid, 578.000000, 44.000000, "100");
PlayerTextDrawFont(playerid, gArmorText[playerid], 2);
PlayerTextDrawLetterSize(playerid, gArmorText[playerid], 0.241666, 0.899999);
PlayerTextDrawTextSize(playerid, gArmorText[playerid], 400.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, gArmorText[playerid], 1);
PlayerTextDrawSetShadow(playerid, gArmorText[playerid], 0);
PlayerTextDrawAlignment(playerid, gArmorText[playerid], 2);
PlayerTextDrawColor(playerid, gArmorText[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, gArmorText[playerid], 255);
PlayerTextDrawBoxColor(playerid, gArmorText[playerid], 50);
PlayerTextDrawUseBox(playerid, gArmorText[playerid], 0);
PlayerTextDrawSetProportional(playerid, gArmorText[playerid], 1);
PlayerTextDrawSetSelectable(playerid, gArmorText[playerid], 0);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, gHealthText); //Shows Textdraw for Player.
TextDrawShowForAll(gHealthText); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, gHealthText); //Hides TextDraw for player.
TextDrawHideForAll(gHealthText); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, gHealthText[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, gHealthText[playerid]); //Hides PlayerTextDraw for player.
