/*
This script has been generated by Nickk's TextDraw editor
Author is Nickk888
*/

//VARIABLES
new Text:textdraw_1;
new Text:textdraw_2;
new Text:textdraw_3;
new Text:textdraw_4;
new Text:textdraw_5;

//TEXTDRAWS
textdraw_1 = TextDrawCreate(326.000000, 393.000000, "_");
TextDrawFont(textdraw_1, 1);
TextDrawLetterSize(textdraw_1, 0.683333, 1.850005);
TextDrawTextSize(textdraw_1, 217.000000, 150.000000);
TextDrawSetOutline(textdraw_1, 1);
TextDrawSetShadow(textdraw_1, 0);
TextDrawAlignment(textdraw_1, 2);
TextDrawColor(textdraw_1, -1);
TextDrawBackgroundColor(textdraw_1, 255);
TextDrawBoxColor(textdraw_1, 9145138);
TextDrawUseBox(textdraw_1, 1);
TextDrawSetProportional(textdraw_1, 1);
TextDrawSetSelectable(textdraw_1, 0);

textdraw_2 = TextDrawCreate(325.000000, 392.000000, "_");
TextDrawFont(textdraw_2, 1);
TextDrawLetterSize(textdraw_2, 0.683333, 1.850005);
TextDrawTextSize(textdraw_2, 217.000000, 150.000000);
TextDrawSetOutline(textdraw_2, 1);
TextDrawSetShadow(textdraw_2, 0);
TextDrawAlignment(textdraw_2, 2);
TextDrawColor(textdraw_2, -1);
TextDrawBackgroundColor(textdraw_2, 255);
TextDrawBoxColor(textdraw_2, 9145138);
TextDrawUseBox(textdraw_2, 1);
TextDrawSetProportional(textdraw_2, 1);
TextDrawSetSelectable(textdraw_2, 0);

textdraw_3 = TextDrawCreate(384.000000, 392.000000, "Next");
TextDrawFont(textdraw_3, 2);
TextDrawLetterSize(textdraw_3, 0.258332, 1.750000);
TextDrawTextSize(textdraw_3, 16.500000, 28.500000);
TextDrawSetOutline(textdraw_3, 1);
TextDrawSetShadow(textdraw_3, 0);
TextDrawAlignment(textdraw_3, 2);
TextDrawColor(textdraw_3, -1);
TextDrawBackgroundColor(textdraw_3, 255);
TextDrawBoxColor(textdraw_3, 200);
TextDrawUseBox(textdraw_3, 0);
TextDrawSetProportional(textdraw_3, 1);
TextDrawSetSelectable(textdraw_3, 1);

textdraw_4 = TextDrawCreate(276.000000, 392.000000, "previous");
TextDrawFont(textdraw_4, 2);
TextDrawLetterSize(textdraw_4, 0.258332, 1.750000);
TextDrawTextSize(textdraw_4, 16.500000, 51.000000);
TextDrawSetOutline(textdraw_4, 1);
TextDrawSetShadow(textdraw_4, 0);
TextDrawAlignment(textdraw_4, 2);
TextDrawColor(textdraw_4, -1);
TextDrawBackgroundColor(textdraw_4, 255);
TextDrawBoxColor(textdraw_4, 200);
TextDrawUseBox(textdraw_4, 0);
TextDrawSetProportional(textdraw_4, 1);
TextDrawSetSelectable(textdraw_4, 1);

textdraw_5 = TextDrawCreate(331.000000, 392.000000, "buy");
TextDrawFont(textdraw_5, 2);
TextDrawLetterSize(textdraw_5, 0.258332, 1.750000);
TextDrawTextSize(textdraw_5, 16.500000, 28.500000);
TextDrawSetOutline(textdraw_5, 1);
TextDrawSetShadow(textdraw_5, 0);
TextDrawAlignment(textdraw_5, 2);
TextDrawColor(textdraw_5, -1);
TextDrawBackgroundColor(textdraw_5, 255);
TextDrawBoxColor(textdraw_5, 200);
TextDrawUseBox(textdraw_5, 0);
TextDrawSetProportional(textdraw_5, 1);
TextDrawSetSelectable(textdraw_5, 1);


//SHOW/HIDE
TextDrawShowForPlayer(playerid, textdraw_0); //Shows Textdraw for Player.
TextDrawShowForAll(textdraw_0); //Shows Textdraw for all players.

TextDrawHideForPlayer(playerid, textdraw_0); //Hides TextDraw for player.
TextDrawHideForAll(textdraw_0); //Hides Textdraw for all players.

PlayerTextDrawShow(playerid, textdraw_0[playerid]); //Shows PlayerTextDraw for player.
PlayerTextDrawHide(playerid, textdraw_0[playerid]); //Hides PlayerTextDraw for player.

SelectTextDraw(playerid, 0xFF0000FF); //Shows cursor for player to select textdraw